server:
  port: 80

spring:
  application:
    name: FabricJDK
  datasource:
    url: jdbc:mysql://localhost:3306/fabric_db?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

fabric:
  network-connection-config-path: src/main/resources/connection.json
  certificate-path: src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
  private-key-path: src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  msp-id: Org1MSP
  tls-cert-path: src/main/resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  channel: mychannel
logging:
  level:
    com.example: trace


